language: ruby
rvm:
  - 2.2.6
  - 2.3.3

services:
  - postgresql

addons:
  postgresql: "9.5"

script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database event_tracker_test;' -U postgres
  - bin/rake db:setup RAILS_ENV=test
  - bin/rake