# Use Postgres for database in all environments
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: karlhughes
  password:

development:
  <<: *default
  database: event_tracker_dev

test:
  <<: *default
  database: event_tracker_test

production:
  <<: *default
  database: event_tracker_prod
  url: <%= ENV['DATABASE_URL'] %>
