# Postgres DB Adapter
#   gem install pg
#
#   Ensure the Postgres gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: karlhughes
  password:

development:
  <<: *default
  database: event_tracker_dev

test:
  <<: *default
  database: event_tracker_test

production:
  <<: *default
  database: event_tracker_prod
